name: web-cluster

networks:
  internal:
    driver: bridge

    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1

services:
  api-1:
    image: node:22
    hostname: api-1
    working_dir: /application/
    volumes:
      - type: bind
        source: ./
        target: /application/
    networks:
      internal:
        ipv4_address: 192.168.2.2
    command: ["npm", "run", "server"]
    environment:
      HOST: 192.168.2.2
      DATABASE_CONNECTION_STRING: mysql://root:root@192.168.2.6:3306/web

  api-2:
    image: node:22
    hostname: api-2
    working_dir: /application/
    volumes:
      - type: bind
        source: ./
        target: /application/
    networks:
      internal:
        ipv4_address: 192.168.2.3
    command: ["npm", "run", "server"]
    environment:
      HOST: 192.168.2.3
      DATABASE_CONNECTION_STRING: mysql://root:root@192.168.2.6:3306/web

  api-3:
    image: node:22
    hostname: api-3
    working_dir: /application/
    volumes:
      - type: bind
        source: ./
        target: /application/
    networks:
      internal:
        ipv4_address: 192.168.2.4
    command: ["npm", "run", "server"]
    environment:
      HOST: 192.168.2.4
      DATABASE_CONNECTION_STRING: mysql://root:root@192.168.2.6:3306/web

  load-balancer:
    image: node:22
    working_dir: /application/
    volumes:
      - type: bind
        source: ./
        target: /application/
    networks:
      internal:
        ipv4_address: 192.168.2.5
    command: ["npm", "run", "load-balancer"]
    environment:
      SERVERS: "192.168.2.2:3000,192.168.2.3:3000,192.168.2.4:3000"
      DATABASE_CONNECTION_STRING: mysql://root:root@192.168.2.6:3306/web
    ports:
      - "3000:3000"

  database:
    image: mysql:9
    working_dir: /application/
    volumes:
      - type: bind
        source: ./.database
        target: /var/lib/mysql
    networks:
      internal:
        ipv4_address: 192.168.2.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "web"
      MYSQL_ROOT_PASSWORD: "root"
